# Import all models so SQLAlchemy registers them with Base.metadata.
# Alembic's env.py imports Base from database.py — if any model isn't imported here,
# its table will be missing from the autogenerated migration.
from app.models.user import User
from app.models.workspace import Workspace, WorkspaceMember
from app.models.integration import Integration
from app.models.incident import Incident, IncidentEvent
from app.models.action_item import ActionItem
from app.models.transcript import TranscriptChunk
from app.models.deep_dive import DeepDiveResult

__all__ = [
    "User",
    "Workspace",
    "WorkspaceMember",
    "Integration",
    "Incident",
    "IncidentEvent",
    "ActionItem",
    "TranscriptChunk",
    "DeepDiveResult",
]
